# -*- coding: utf-8 -*-
"""Data_Preprocessing_Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_rn6rCbwOGub_MSkf9APBeiswJwROq3g
"""

from google.colab import drive
drive.mount('/content/drive')

#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#importing the dataset

dataset=pd.read_csv('/content/drive/My Drive/Data.csv')

X=dataset.iloc[:,:-1].values

Y=dataset.iloc[:,-1].values

# Taking care of the missing data

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

# Labeling the code

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X=LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])

from sklearn.compose import ColumnTransformer
# Country column
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
X = ct.fit_transform(X)

labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)